"""L1 用户域 — 学习者身份、上下文经纪、会话管理、HiTL 协同.

L1 层是 Dy3+ Polaris 多智能体系统的用户入口层，负责:
1. 用户身份认证与权限控制 (RBAC + ABAC 混合模型)
2. 学习上下文经纪 (Learning Context Broker)
3. 学习会话管理与 Session Fork
4. 人机协同 (Human-in-the-Loop)
5. 隐私保护与数据治理

设计依据: 02-设计/L1-用户域设计/layer1-user-domain.html
"""

# T1: 核心数据模型
from dy3_polaris.l1.models import (
    ABACAttributes,
    AccessCheck,
    AgentState,
    AlertType,
    ApprovalDecision,
    ApprovalRequest,
    ApprovalResponse,
    AuditAction,
    AuditLogEntry,
    AuditResult,
    BKTParams,
    BKTUpdate,
    BloomTag,
    CognitiveLoadBreakdown,
    ConfidenceGateResult,
    ContentModality,
    ContextEnvelope,
    DataLevel,
    DecayRequest,
    DesensitizationMethod,
    ElementInteractivity,
    EmergencyAlert,
    EngagementLevel,
    EngagementMetrics,
    EventResult,
    FeedbackCategory,
    FeedbackReport,
    FeedbackType,
    FSRSParameters,
    FSRSCardState,
    FSRSReviewLog,
    GradeLevel,
    HiTLPriority,
    HiTLType,
    IRTAbility,
    IRTItem,
    IRTModel,
    Interaction,
    KnowledgeComponent,
    KnowledgeResult,
    KnowledgeType,
    LabAccessTier,
    LearningContext,
    LearningEfficiency,
    LearningEvent,
    LearningGoal,
    LearningPath,
    LearningPhase,
    LearningSession,
    LearningState,
    MajorDirection,
    MasterySnapshot,
    MasteryTrajectory,
    MasteryTrajectoryPoint,
    MemoryEntry,
    PathNode,
    PathRecommendation,
    Permission,
    PolicyUpdate,
    PrivacyConfig,
    PrivacyEvent,
    ProvenanceRecord,
    ResourceItem,
    ResourceRequest,
    RetentionPhase,
    RetentionPolicy,
    Role,
    SessionAnalytics,
    SessionArtifact,
    SessionCheckpoint,
    SessionFork,
    SessionStatus,
    SessionType,
    StudyBlock,
    StudyPlan,
    TimeConstraint,
    User,
    UserRole,
    UserStatus,
    VARKProfile,
    VARKStyle,
    ZoneOfProximalDevelopment,
)

# T2: 认证与权限控制
from dy3_polaris.l1.auth import (
    AuthenticationError,
    JWTManager,
    L1AuthError,
    LifecycleError,
    PasswordHasher,
    TokenError,
    TokenExpiredError,
    TokenPayload,
    TokenRevokedError,
    UserLifecycleManager,
)
from dy3_polaris.l1.access_control import (
    ABACEvaluator,
    ABACPolicy,
    AccessControlManager,
    AccessDecision,
    AccessDeniedError,
    AccessRequest,
    AccessResult,
    ActionType,
    RBACMatrix,
    ResourceType,
)

# T3: 学习上下文经纪
from dy3_polaris.l1.context_broker import (
    # 异常
    L1ContextError,
    ContextNotFoundError,
    ContextExpiredError,
    ContextValidationError,
    DecayError,
    # 事件采集
    FrontendEvent,
    AgentOutputEvent,
    UserDeclaration,
    ContextCollector,
    # 衰减引擎
    DecayEngine,
    # 缓存
    ContextCache,
    # 核心引擎
    LearningContextBroker,
    # 常量
    CACHE_TTL_SESSION,
    CACHE_TTL_MASTERY,
    CACHE_TTL_GOAL,
    CACHE_TTL_COGNITIVE,
    COGNITIVE_LOAD_BASE,
    COGNITIVE_LOAD_FAST_ANSWER_MS,
    COGNITIVE_LOAD_ERROR_WEIGHT,
    COGNITIVE_LOAD_HELP_WEIGHT,
    REVIEW_URGENCY_THRESHOLD,
)

# T4: 人机协同 (HiTL)
from dy3_polaris.l1.hitl_manager import (
    # 异常
    L1HiTLError,
    ConfidenceGateError,
    ApprovalError,
    FeedbackError,
    EmergencyError,
    # 交互模式
    InteractionMode,
    # 置信度门控
    ConfidenceGate,
    GateDecision,
    GateResult,
    # 紧急检测
    EmergencyDetector,
    # 反馈回路
    FeedbackLoop,
    FeedbackRoutingResult,
    # 纠错型结果
    CorrectionResult,
    # 核心管理器
    HiTLManager,
    # 常量
    APPROVAL_TIMEOUT_SECONDS,
    APPROVAL_TIMEOUT_MS,
    MAX_CORRECTION_RETRIES,
    EMERGENCY_RESPONSE_MS,
    EMERGENCY_COOLDOWN_MS,
    FEEDBACK_HISTORY_LIMIT,
    ALERT_HISTORY_LIMIT,
)

# T5: 学习会话管理
from dy3_polaris.l1.session_manager import (
    # 异常
    L1SessionError,
    SessionNotFoundError,
    SessionStateError,
    ForkError,
    CheckpointError,
    # 检查点管理
    CheckpointManager,
    # Fork 管理
    ForkManager,
    # 上下文传递
    ContextTransfer,
    # 核心管理器
    LearningSessionManager,
    # 常量
    MAX_FORK_DEPTH,
    MAX_FORK_CONCURRENCY,
    MAX_ACTIVE_SESSIONS_PER_USER,
    SESSION_IDLE_TIMEOUT_MS,
    SESSION_IDLE_TIMEOUT_S,
    CHECKPOINT_PREFIX,
)

# T6: 隐私治理
from dy3_polaris.l1.privacy_governance import (
    # 异常
    L1PrivacyError,
    DataClassificationError,
    DesensitizationError,
    RetentionExecutionError,
    AuditLogError,
    PrivacyViolationError,
    # 数据分级
    DataClassifier,
    # 脱敏引擎
    DesensitizationEngine,
    # 留存管理
    RetentionManager,
    RetentionAction,
    RetentionResult,
    # 审计日志
    AuditLogger,
    # 事件通知
    PrivacyEventNotifier,
    # 统一管理器
    PrivacyGovernanceManager,
    # 常量
    MS_PER_DAY,
    RETENTION_ARCHIVE_DAYS,
    RETENTION_ANONYMIZE_DAYS,
    GENESIS_HASH,
    PSEUDO_ID_PREFIX,
)

# T7: API 与集成
from dy3_polaris.l1.api_integration import (
    # 异常
    L1APIError,
    APIKeyError,
    APIRateLimitError,
    IdempotencyError,
    WebhookError,
    LayerInterfaceError,
    # 统一响应
    ok_response,
    error_response,
    paginated_response,
    # API Key 管理
    APIKeyPayload,
    APIKeyManager,
    # 游标分页
    Page,
    CursorPaginator,
    # 幂等性
    IdempotencyManager,
    # 限流
    TokenBucketRateLimiter,
    # Webhook
    WebhookEndpoint,
    WebhookManager,
    # SSE 事件流
    SSEEvent,
    EventStreamManager,
    # 中间件
    AuthMiddleware,
    ABACMiddleware,
    AuditMiddleware,
    # REST API 路由器
    L1APIRouter,
    # 层间接口
    LayerInterfaces,
    # 常量
    API_VERSION,
    API_PREFIX,
    API_KEY_PREFIX,
    API_KEY_BYTES,
    API_KEY_DEFAULT_TTL,
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    IDEMPOTENCY_DEFAULT_TTL,
    DEFAULT_BUCKET_CAPACITY,
    DEFAULT_REFILL_RATE,
)

__all__ = [
    # T1: 核心数据模型 (82 个公开类)
    "ABACAttributes",
    "AccessCheck",
    "AgentState",
    "AlertType",
    "ApprovalDecision",
    "ApprovalRequest",
    "ApprovalResponse",
    "AuditAction",
    "AuditLogEntry",
    "AuditResult",
    "BKTParams",
    "BKTUpdate",
    "BloomTag",
    "CognitiveLoadBreakdown",
    "ConfidenceGateResult",
    "ContentModality",
    "ContextEnvelope",
    "DataLevel",
    "DecayRequest",
    "DesensitizationMethod",
    "ElementInteractivity",
    "EmergencyAlert",
    "EngagementLevel",
    "EngagementMetrics",
    "EventResult",
    "FeedbackCategory",
    "FeedbackReport",
    "FeedbackType",
    "FSRSParameters",
    "FSRSCardState",
    "FSRSReviewLog",
    "GradeLevel",
    "HiTLPriority",
    "HiTLType",
    "IRTAbility",
    "IRTItem",
    "IRTModel",
    "Interaction",
    "KnowledgeComponent",
    "KnowledgeResult",
    "KnowledgeType",
    "LabAccessTier",
    "LearningContext",
    "LearningEfficiency",
    "LearningEvent",
    "LearningGoal",
    "LearningPath",
    "LearningPhase",
    "LearningSession",
    "LearningState",
    "MajorDirection",
    "MasterySnapshot",
    "MasteryTrajectory",
    "MasteryTrajectoryPoint",
    "MemoryEntry",
    "PathNode",
    "PathRecommendation",
    "Permission",
    "PolicyUpdate",
    "PrivacyConfig",
    "PrivacyEvent",
    "ProvenanceRecord",
    "ResourceItem",
    "ResourceRequest",
    "RetentionPhase",
    "RetentionPolicy",
    "Role",
    "SessionAnalytics",
    "SessionArtifact",
    "SessionCheckpoint",
    "SessionFork",
    "SessionStatus",
    "SessionType",
    "StudyBlock",
    "StudyPlan",
    "TimeConstraint",
    "User",
    "UserRole",
    "UserStatus",
    "VARKProfile",
    "VARKStyle",
    "ZoneOfProximalDevelopment",
    # T2: 认证
    "AuthenticationError",
    "JWTManager",
    "L1AuthError",
    "LifecycleError",
    "PasswordHasher",
    "TokenError",
    "TokenExpiredError",
    "TokenPayload",
    "TokenRevokedError",
    "UserLifecycleManager",
    # T2: 权限控制
    "ABACEvaluator",
    "ABACPolicy",
    "AccessControlManager",
    "AccessDecision",
    "AccessDeniedError",
    "AccessRequest",
    "AccessResult",
    "ActionType",
    "RBACMatrix",
    "ResourceType",
    # T3: 学习上下文经纪
    "L1ContextError",
    "ContextNotFoundError",
    "ContextExpiredError",
    "ContextValidationError",
    "DecayError",
    "FrontendEvent",
    "AgentOutputEvent",
    "UserDeclaration",
    "ContextCollector",
    "DecayEngine",
    "ContextCache",
    "LearningContextBroker",
    "CACHE_TTL_SESSION",
    "CACHE_TTL_MASTERY",
    "CACHE_TTL_GOAL",
    "CACHE_TTL_COGNITIVE",
    "COGNITIVE_LOAD_BASE",
    "COGNITIVE_LOAD_FAST_ANSWER_MS",
    "COGNITIVE_LOAD_ERROR_WEIGHT",
    "COGNITIVE_LOAD_HELP_WEIGHT",
    "REVIEW_URGENCY_THRESHOLD",
    # T4: 人机协同
    "L1HiTLError",
    "ConfidenceGateError",
    "ApprovalError",
    "FeedbackError",
    "EmergencyError",
    "InteractionMode",
    "ConfidenceGate",
    "GateDecision",
    "GateResult",
    "EmergencyDetector",
    "FeedbackLoop",
    "FeedbackRoutingResult",
    "CorrectionResult",
    "HiTLManager",
    "APPROVAL_TIMEOUT_SECONDS",
    "APPROVAL_TIMEOUT_MS",
    "MAX_CORRECTION_RETRIES",
    "EMERGENCY_RESPONSE_MS",
    "EMERGENCY_COOLDOWN_MS",
    "FEEDBACK_HISTORY_LIMIT",
    "ALERT_HISTORY_LIMIT",
    # T5: 学习会话管理
    "L1SessionError",
    "SessionNotFoundError",
    "SessionStateError",
    "ForkError",
    "CheckpointError",
    "CheckpointManager",
    "ForkManager",
    "ContextTransfer",
    "LearningSessionManager",
    "MAX_FORK_DEPTH",
    "MAX_FORK_CONCURRENCY",
    "MAX_ACTIVE_SESSIONS_PER_USER",
    "SESSION_IDLE_TIMEOUT_MS",
    "SESSION_IDLE_TIMEOUT_S",
    "CHECKPOINT_PREFIX",
    # T6: 隐私治理
    "L1PrivacyError",
    "DataClassificationError",
    "DesensitizationError",
    "RetentionExecutionError",
    "AuditLogError",
    "PrivacyViolationError",
    "DataClassifier",
    "DesensitizationEngine",
    "RetentionManager",
    "RetentionAction",
    "RetentionResult",
    "AuditLogger",
    "PrivacyEventNotifier",
    "PrivacyGovernanceManager",
    "MS_PER_DAY",
    "RETENTION_ARCHIVE_DAYS",
    "RETENTION_ANONYMIZE_DAYS",
    "GENESIS_HASH",
    "PSEUDO_ID_PREFIX",
    # T7: API 与集成
    "L1APIError",
    "APIKeyError",
    "APIRateLimitError",
    "IdempotencyError",
    "WebhookError",
    "LayerInterfaceError",
    "ok_response",
    "error_response",
    "paginated_response",
    "APIKeyPayload",
    "APIKeyManager",
    "Page",
    "CursorPaginator",
    "IdempotencyManager",
    "TokenBucketRateLimiter",
    "WebhookEndpoint",
    "WebhookManager",
    "SSEEvent",
    "EventStreamManager",
    "AuthMiddleware",
    "ABACMiddleware",
    "AuditMiddleware",
    "L1APIRouter",
    "LayerInterfaces",
    "API_VERSION",
    "API_PREFIX",
    "API_KEY_PREFIX",
    "API_KEY_BYTES",
    "API_KEY_DEFAULT_TTL",
    "DEFAULT_PAGE_SIZE",
    "MAX_PAGE_SIZE",
    "IDEMPOTENCY_DEFAULT_TTL",
    "DEFAULT_BUCKET_CAPACITY",
    "DEFAULT_REFILL_RATE",
]

# T8: 执行引擎 (FSRS 调度 / IRT 估计 / VARK 采集)
from dy3_polaris.l1.fsrs_scheduler import FSRSScheduler
from dy3_polaris.l1.fsrs_optimizer import FSRSOptimizer, RegretMinimizer
from dy3_polaris.l1.irt_estimator import IRTEstimator
from dy3_polaris.l1.vark_collector import VARKSurveyCollector

__all__.extend([
    # T8: 执行引擎
    "FSRSScheduler",
    "FSRSOptimizer",
    "RegretMinimizer",
    "IRTEstimator",
    "VARKSurveyCollector",
])
